using Docile, Lexicon, Merlin

const api_directory = "api"
const modules = [Merlin]

cd(dirname(@__FILE__)) do
    # Generate and save the contents of docstrings as markdown files.
    index  = Index()
    for mod in modules
        Lexicon.update!(index, save(joinpath(api_directory, "$(mod).md"), mod))
    end
    save(joinpath(api_directory, "index.md"), index; md_subheader = :category)

    # Add a reminder not to edit the generated files.
    #open(joinpath(api_directory, "README.md"), "w") do f
    #    print(f, """
    #    Files in this directory are generated using the `build.jl` script. Make
    #    all changes to the originating docstrings/files rather than these ones.
    #    """)
    #end
end


cd(dirname(dirname(@__FILE__))) do
    yaml = """
      # This is automatically generated by docs/build.jl. Edit that file if you
      # wish to make any permenant changes.
      site_name: Merlin.jl
      site_description: Merlin.jl Flexible neural network library in Julia
      site_author: Hiroyuki Shindo
      repo_name: GitHub
      # site_favicon: favicon.ico
      docs_dir: 'docs'
      site_dir: 'site'
      repo_url: https://github.com/hshind/Merlin.jl/
      pages:
      - Home: 'index.md'
    """

    open("mkdocs.yml", "w") do f
        write(f, yaml)
    end
end
