const DEFINE = Dict{Symbol,Symbol}()

if API_VERSION >= 3020
    DEFINE[:cuDeviceTotalMem]           = :cuDeviceTotalMem_v2
    DEFINE[:cuCtxCreate]                = :cuCtxCreate_v2
    DEFINE[:cuModuleGetGlobal]          = :cuModuleGetGlobal_v2
    DEFINE[:cuMemGetInfo]               = :cuMemGetInfo_v2
    DEFINE[:cuMemAlloc]                 = :cuMemAlloc_v2
    DEFINE[:cuMemAllocPitch]            = :cuMemAllocPitch_v2
    DEFINE[:cuMemFree]                  = :cuMemFree_v2
    DEFINE[:cuMemGetAddressRange]       = :cuMemGetAddressRange_v2
    DEFINE[:cuMemAllocHost]             = :cuMemAllocHost_v2
    DEFINE[:cuMemHostGetDevicePointer]  = :cuMemHostGetDevicePointer_v2
    DEFINE[:cuMemcpyHtoD]               = :cuMemcpyHtoD_v2
    DEFINE[:cuMemcpyDtoH]               = :cuMemcpyDtoH_v2
    DEFINE[:cuMemcpyDtoD]               = :cuMemcpyDtoD_v2
    DEFINE[:cuMemcpyDtoA]               = :cuMemcpyDtoA_v2
    DEFINE[:cuMemcpyAtoD]               = :cuMemcpyAtoD_v2
    DEFINE[:cuMemcpyHtoA]               = :cuMemcpyHtoA_v2
    DEFINE[:cuMemcpyAtoH]               = :cuMemcpyAtoH_v2
    DEFINE[:cuMemcpyAtoA]               = :cuMemcpyAtoA_v2
    DEFINE[:cuMemcpyHtoAAsync]          = :cuMemcpyHtoAAsync_v2
    DEFINE[:cuMemcpyAtoHAsync]          = :cuMemcpyAtoHAsync_v2
    DEFINE[:cuMemcpy2D]                 = :cuMemcpy2D_v2
    DEFINE[:cuMemcpy2DUnaligned]        = :cuMemcpy2DUnaligned_v2
    DEFINE[:cuMemcpy3D]                 = :cuMemcpy3D_v2
    DEFINE[:cuMemcpyHtoDAsync]          = :cuMemcpyHtoDAsync_v2
    DEFINE[:cuMemcpyDtoHAsync]          = :cuMemcpyDtoHAsync_v2
    DEFINE[:cuMemcpyDtoDAsync]          = :cuMemcpyDtoDAsync_v2
    DEFINE[:cuMemcpy2DAsync]            = :cuMemcpy2DAsync_v2
    DEFINE[:cuMemcpy3DAsync]            = :cuMemcpy3DAsync_v2
    DEFINE[:cuMemsetD8]                 = :cuMemsetD8_v2
    DEFINE[:cuMemsetD16]                = :cuMemsetD16_v2
    DEFINE[:cuMemsetD32]                = :cuMemsetD32_v2
    DEFINE[:cuMemsetD2D8]               = :cuMemsetD2D8_v2
    DEFINE[:cuMemsetD2D16]              = :cuMemsetD2D16_v2
    DEFINE[:cuMemsetD2D32]              = :cuMemsetD2D32_v2
    DEFINE[:cuArrayCreate]              = :cuArrayCreate_v2
    DEFINE[:cuArrayGetDescriptor]       = :cuArrayGetDescriptor_v2
    DEFINE[:cuArray3DCreate]            = :cuArray3DCreate_v2
    DEFINE[:cuArray3DGetDescriptor]     = :cuArray3DGetDescriptor_v2
    DEFINE[:cuTexRefSetAddress]         = :cuTexRefSetAddress_v2
    DEFINE[:cuTexRefGetAddress]         = :cuTexRefGetAddress_v2
    DEFINE[:cuGraphicsResourceGetMappedPointer] = :cuGraphicsResourceGetMappedPointer_v2
end
if API_VERSION >= 4000
    DEFINE[:cuCtxDestroy]               = :cuCtxDestroy_v2
    DEFINE[:cuCtxPopCurrent]            = :cuCtxPopCurrent_v2
    DEFINE[:cuCtxPushCurrent]           = :cuCtxPushCurrent_v2
    DEFINE[:cuStreamDestroy]            = :cuStreamDestroy_v2
    DEFINE[:cuEventDestroy]             = :cuEventDestroy_v2
end
if API_VERSION >= 4010
    DEFINE[:cuTexRefSetAddress2D]       = :cuTexRefSetAddress2D_v3
end
if API_VERSION >= 6050
    DEFINE[:cuLinkCreate]              = :cuLinkCreate_v2
    DEFINE[:cuLinkAddData]             = :cuLinkAddData_v2
    DEFINE[:cuLinkAddFile]             = :cuLinkAddFile_v2
end
if API_VERSION >= 6050
    DEFINE[:cuMemHostRegister]         = :cuMemHostRegister_v2
    DEFINE[:cuGraphicsResourceSetMapFlags] = :cuGraphicsResourceSetMapFlags_v2
end
if 3020 <= API_VERSION < 4010
    DEFINE[:cuTexRefSetAddress2D]      = :cuTexRefSetAddress2D_v2
end

const CUDA_SUCCESS                              = Cint(0)
const CUDA_ERROR_INVALID_VALUE                  = Cint(1)
const CUDA_ERROR_OUT_OF_MEMORY                  = Cint(2)
const CUDA_ERROR_NOT_INITIALIZED                = Cint(3)
const CUDA_ERROR_DEINITIALIZED                  = Cint(4)
const CUDA_ERROR_PROFILER_DISABLED              = Cint(5)
const CUDA_ERROR_PROFILER_NOT_INITIALIZED       = Cint(6)
const CUDA_ERROR_PROFILER_ALREADY_STARTED       = Cint(7)
const CUDA_ERROR_PROFILER_ALREADY_STOPPED       = Cint(8)
const CUDA_ERROR_NO_DEVICE                      = Cint(100)
const CUDA_ERROR_INVALID_DEVICE                 = Cint(101)
const CUDA_ERROR_INVALID_IMAGE                  = Cint(200)
const CUDA_ERROR_INVALID_CONTEXT                = Cint(201)
const CUDA_ERROR_CONTEXT_ALREADY_CURRENT        = Cint(202)
const CUDA_ERROR_MAP_FAILED                     = Cint(205)
const CUDA_ERROR_UNMAP_FAILED                   = Cint(206)
const CUDA_ERROR_ARRAY_IS_MAPPED                = Cint(207)
const CUDA_ERROR_ALREADY_MAPPED                 = Cint(208)
const CUDA_ERROR_NO_BINARY_FOR_GPU              = Cint(209)
const CUDA_ERROR_ALREADY_ACQUIRED               = Cint(210)
const CUDA_ERROR_NOT_MAPPED                     = Cint(211)
const CUDA_ERROR_NOT_MAPPED_AS_ARRAY            = Cint(212)
const CUDA_ERROR_NOT_MAPPED_AS_POINTER          = Cint(213)
const CUDA_ERROR_ECC_UNCORRECTABLE              = Cint(214)
const CUDA_ERROR_UNSUPPORTED_LIMIT              = Cint(215)
const CUDA_ERROR_CONTEXT_ALREADY_IN_USE         = Cint(216)
const CUDA_ERROR_PEER_ACCESS_UNSUPPORTED        = Cint(217)
const CUDA_ERROR_INVALID_PTX                    = Cint(218)
const CUDA_ERROR_INVALID_GRAPHICS_CONTEXT       = Cint(219)
const CUDA_ERROR_NVLINK_UNCORRECTABLE           = Cint(220)
const CUDA_ERROR_JIT_COMPILER_NOT_FOUND         = Cint(221)
const CUDA_ERROR_INVALID_SOURCE                 = Cint(300)
const CUDA_ERROR_FILE_NOT_FOUND                 = Cint(301)
const CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND = Cint(302)
const CUDA_ERROR_SHARED_OBJECT_INIT_FAILED      = Cint(303)
const CUDA_ERROR_OPERATING_SYSTEM               = Cint(304)
const CUDA_ERROR_INVALID_HANDLE                 = Cint(400)
const CUDA_ERROR_NOT_FOUND                      = Cint(500)
const CUDA_ERROR_NOT_READY                      = Cint(600)
const CUDA_ERROR_ILLEGAL_ADDRESS                = Cint(700)
const CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES        = Cint(701)
const CUDA_ERROR_LAUNCH_TIMEOUT                 = Cint(702)
const CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING  = Cint(703)
const CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED    = Cint(704)
const CUDA_ERROR_PEER_ACCESS_NOT_ENABLED        = Cint(705)
const CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE         = Cint(708)
const CUDA_ERROR_CONTEXT_IS_DESTROYED           = Cint(709)
const CUDA_ERROR_ASSERT                         = Cint(710)
const CUDA_ERROR_TOO_MANY_PEERS                 = Cint(711)
const CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED = Cint(712)
const CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED     = Cint(713)
const CUDA_ERROR_HARDWARE_STACK_ERROR           = Cint(714)
const CUDA_ERROR_ILLEGAL_INSTRUCTION            = Cint(715)
const CUDA_ERROR_MISALIGNED_ADDRESS             = Cint(716)
const CUDA_ERROR_INVALID_ADDRESS_SPACE          = Cint(717)
const CUDA_ERROR_INVALID_PC                     = Cint(718)
const CUDA_ERROR_LAUNCH_FAILED                  = Cint(719)
const CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE   = Cint(720)
const CUDA_ERROR_NOT_PERMITTED                  = Cint(800)
const CUDA_ERROR_NOT_SUPPORTED                  = Cint(801)
const CUDA_ERROR_UNKNOWN                        = Cint(999)
